unit TestSignal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Signal, System.Generics.Collections;

type
  // Test methods for class TSignal

  TestTSignal = class(TTestCase)
  strict private
    FSignal: TSignal;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSetState();
  end;

implementation

procedure TestTSignal.SetUp;
begin
  FSignal := TSignal.Create;
end;

procedure TestTSignal.TearDown;
begin
  FSignal.Free;
  FSignal := nil;
end;

procedure TestTSignal.TestSetState;
begin

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSignal.Suite);
end.

