unit TestInputSignalsController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, InputSignalsController, Vcl.ExtCtrls, Signal, System.Classes;

type
  // Test methods for class TInputSignalsController

  TestTInputSignalsController = class(TTestCase)
  strict private
    FInputSignalsController: TInputSignalsController;
  public
    procedure TearDown; override;
  published
    procedure TestCheckDetectorsState;
  end;

implementation



procedure TestTInputSignalsController.TearDown;
begin
  FInputSignalsController.Free;
  FInputSignalsController := nil;
end;

procedure TestTInputSignalsController.TestCheckDetectorsState;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FInputSignalsController.CheckDetectorsState(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTInputSignalsController.Suite);
end.

