unit TestDetectorController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Classes, Vcl.ExtCtrls, DetectorController;

type
  // Test methods for class TDetectorController

  TestTDetectorController = class(TTestCase)
  strict private
    FDetectorController: TDetectorController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetInstance;
  end;

implementation

procedure TestTDetectorController.SetUp;
begin

end;

procedure TestTDetectorController.TearDown;
begin
  FDetectorController.Free;
  FDetectorController := nil;
end;

procedure TestTDetectorController.TestGetInstance;
var
  ReturnValue: TDetectorController;
begin
  ReturnValue := FDetectorController.GetInstance;
  CheckNotNull(ReturnValue);
  CheckIs(ReturnValue,TDetectorController);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDetectorController.Suite);
end.

